import { Header, MessageBar, StoreProvider } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <StoreProvider>
        <body className="grid grid-cols-12 gap-x-8 min-h-full bg-slate-100">
          <Header />
          <main className=" bg-white col-span-10 col-start-2 mb-2">
            {children}
          </main>
          <MessageBar />
        </body>
      </StoreProvider>
    </html>
  )
}
